---
services:
  libreoffice-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreoffice-converter
    env_file:
      - path: compose.env
        required: false
    ports:
      - "5000:5000"
    restart: unless-stopped
