---
services:
  libreoffice-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreoffice-converter
#    environment:
#      - FLASK_DEBUG=1
#      - APP_TEMP_DIR=/tmp/app_temp
#      - APP_DELETE_FILES=false
    ports:
      - "5000:5000"
    restart: unless-stopped
