[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "libreoffice-converter"
version = "0.1.0"
description = "Flask app exposing Libreoffice document conversion for browser and API clients"
dependencies = [
    "flask~=3.0.3",
]
